import { FrameCube } from '../../components';
import { Coffee } from '../../components';
import { Graph } from '../../components';
import { Column } from '../../components';
import { Wall } from '../../components';
import { TextPortion } from '../../components';
import { TickerLine } from '../../components';
import { EndBox } from '../../components';
import { Spread } from '../../components';

export const welcomeSec = {
    lightBg: '',
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightText: true,
    lightTextDesc: false,
    lightTextDescTwo: true, 
    topLine: '',
    headline: 'Power up your team with Keppa.',
    buttonLabel: '',
    description: '👉 Get started right away',
    descriptionTwo: '👇 Learn all about Keppa', 
    featuredImg: require('../../assets/images/keppa-object-02.png').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,
    threeDee: <Wall />,
    backColor: true,
};

export const homeObjOne = {
    lightBg: true,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: '',
    headline: 'Keppa is most certainly not real.',
    buttonLabel: 'Saber mas sobre el proyecto',
    description: 'With Keppa you can organize data better and increase your overall production. Although this product is not real or sensical, it served to help me create a mock up website using react-three-fiber.', 
    featuredImg: require('../../assets/images/keppa-object-02.png').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,
    thirdOne: false,
    single: true,
    isLink: true,   
    wantImg: true, 
    threeDee: <Spread />,
};


export const homeObjTwo = {
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: '',
    headline: '',
    buttonLabel: '',
    description: '', 
    featuredImg: require('../../assets/images/keppa-object-02.png').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,
    thirdOne: true,
    dissapear: true,
    frameCube: true,
    spacingOne: <FrameCube />,
    spacingTwo: <Coffee />,
    spacingThree: <Graph />,
    toTheBack: <TickerLine />,
};

export const homeObjThree = {
    lightBg: true,
    primary: true,
    imgStart: true,
    lightTopLine: true,
    lightText: true,
    lightTextDesc: false, 
    extraBig: true,
    topLine: '',
    headline: '',
    buttonLabel: '',
    description: '', 
    featuredImg: require('../../assets/images/3windowsS.png').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,    
    thirdOne: true,
    isLink: true,
    threeDee: <Column />,
};

export const homeObjFour = {
    lightBg: true,
    primary: true,
    imgStart: false,
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: '',
    headline: 'Keppa`p with the lastest data trends!',
    buttonLabel: 'View Products ',
    descriptionTwo: 'By using Keppa, you have access to numerous diagraming tools and live monitoring apps. Our mission is to actively update and introduce new features.',
    wantImg: true,
    featuredImg: require('../../assets/images/keppa-object-02.png').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,
    thirdOne: false,
    single: true,
    isLink: false,
};

export const homeObjFive = {
    lightBg: '',
    primary: true,
    imgStart: true,
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true, 
    topLine: '',
    headline: 'Dig in even more!',
    buttonLabel: 'Go to Docs ',
    description: 'Check out our "Docs" page to better understand the foundation of our applications.', 
    wantImg: true,
    featuredImg: require('../../assets/images/keppa-object-02.png').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,
    thirdOne: false,
    single: true,
    isLink: false,
    threeDee: <EndBox />,
};
